[meta]
name = "Better Chat"
author = "Miss"
category = "Better Suite"

siteid = 134
version = "1.0.1"

[script]
dependencies = [ "NadeoServices" ]

exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]

imports = [ "Icons.as", "Formatting.as", "Permissions.as", "Time.as" ]
timeout = 0
